# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[per-file-ignores]
"__init__.py" = ["E402"]
"**/{testing,tests,docs,tools,Documentation}" = ["E402"]

# Ignore `F811` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[per-file-ignores]
"__init__.py" = ["F811"]
"**/{testing,tests,docs,tools,Documentation}" = ["F811"]
